name: Keep Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://protrack-8jrbox7zumyvq3vfju8dnf.streamlit.app/
